apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestofblocket
spec:
  selector:
    matchLabels:
      app: bestofblocket
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: bestofblocket
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: nginx
          configMap:
            name: nginx
      containers:
        - name: bestofblocket
          image: europe-west1-docker.pkg.dev/roiiogcloud/bestofblocket/bestofblocket:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/
          ports:
            - name: nginx
              containerPort: 8500
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: bestofblocket-db-secret
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestofblocket-db-secret
                  key: password
            - name: GUNICORN_CMD_ARGS
              value: "--bind=:8201 --workers=1 --daemon"
      terminationGracePeriodSeconds: 25
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"http2":"HTTP2"}'
  labels:
    app: bestofblocket
  name: bestofblocket
spec:
  type: ClusterIP
  ports:
    - port: 8500
      targetPort: 8200
      protocol: TCP
      name: http2
  selector:
    app: bestofblocket
