apiVersion: apps/v1
kind: Deployment
metadata:
  name: bestofblocket
spec:
  selector:
    matchLabels:
      app: bestofblocket
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: bestofblocket
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-spot
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: bestofblocket
          image: europe-west1-docker.pkg.dev/roiiogcloud/bestofblocket/bestofblocket:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8500
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: bestofblocket-db-secret
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bestofblocket-db-secret
                  key: password
            - name: DJANGO_SETTINGS_MODULE
              value: "bestofblocket.conf.settings.production"
            - name: GUNICORN_CMD_ARGS
              value: "--bind=:8500 --workers=1 --threads 2 --max-requests=100000 --timeout=65 --error-logfile=- --access-logfile=- --worker-tmp-dir=/dev/shm --preload"
      terminationGracePeriodSeconds: 25
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bestofblocket
  name: bestofblocket
spec:
  selector:
    app: bestofblocket
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
