apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bestofblocket-se
spec:
  secretName: bestofblocket-se-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.bestofblocket.se"
    - "bestofblocket.se"
