apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bestofblocket
  labels:
    app: bestofblocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bestofblocket
  template:
    metadata:
      labels:
        app: bestofblocket
    spec:
      containers:
      - name: bestofblocket
        image: gcr.io/roiiogcloud/bestofblocket:latest
        imagePullPolicy: Always
        ports:
        - name: gunicorn
          containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-db-secret
                key: password
          - name: GUNICORN_CMD_ARGS
            value: "--bind=:8000 --workers=1"
---
apiVersion: v1
kind: Service
metadata:
  name: bestofblocket-service
  labels:
    app: bestofblocket
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: bestofblocket
  type: ClusterIP