name: Linters

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ruff
        uses: astral-sh/ruff-action@v3
